spring:
  datasource:
    url: jdbc:h2:mem:test;IFEXISTS=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: embedded
  h2:
    console:
      enabled: true

